name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Verificar se a AWS CLI já está instalada
        run: |
          if ! command -v aws &> /dev/null
          then
              echo "AWS CLI não encontrada. Instalando..."
              curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
          else
              echo "AWS CLI já está instalada."
          fi
          aws --version

      - name: Instalar dependências
        run: npm install

      - name: Configurar credenciais AWS para Serverless Framework
        run: |
          mkdir -p ~/.aws
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ vars.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ vars.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=us-east-1" >> ~/.aws/config

      - name: Mostrar valores das credenciais
        run: |
          cat ~/.aws/credentials
          cat ~/.aws/config

      - name: Implante a função Lambda
        run: |
          npm install -g serverless
          sls deploy
