name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Instalar AWS CLI
        run: |
          # Instalação da AWS CLI usando o utilitário padrão do Docker
          docker run --rm -v $(pwd):/app -w /app amazon/aws-cli aws --version

      - name: Instalar dependências
        run: npm install

      - name: Configurar credenciais AWS para Serverless Framework
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Implante a função Lambda
        run: |
          npm install -g serverless
          sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
